### ISSUE TITLE
[Release Plan] Steps to Release v0.1

### ISSUE THREAD

**Issue by Paebbels** [edaa-org/pyEDAA.ProjectModel#9]
**The following steps are required for a v0.1 release:**
* [x] [Moving more Version classes to a separate repository](https://github.com/edaa-org/pyEDAA.ProjectModel/issues/2)
  * [x] Rename `pySystemVerilogModel` to `pySVModel`
* [x] Review documentation
* [x] Make repository public
  * [x] Review shields - especially URLs and IDs/tokens

**The following steps are optional for a v0.1 release:**
* [x] Push HTML documentation to GitHub Pages in a standalone job depending on previous jobs
  * [x] Collect BuildTheDocs outputs in an artifact for later publishing
    * [x] **Disable direct publishing from BTD containerized job**
  * [x] Collect code coverage as HTML report in an artifact for later publishing
  * [x] Collect static type-checking (by mypy) as HTML report in an artifact for later publishing
* [ ] Create a script to use the pull-request text as release text (#20)
  (Based on PR name matching the tag name used to run a release pipeline.)
* [x] Add a different icon for the mypy static type-checking job.

**After release items:**
* [x] [Setup Codacy when going Public](https://github.com/edaa-org/pyEDAA.ProjectModel/issues/5)
